# Generated by Django 6.0.4 on 2026-05-06 13:28
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_slug'),
    ]

    operations = [
        TrigramExtension(),
    ]
